### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by JeremyIglehart** [atom-minimap/minimap-highlight-selected#27]
[Enter steps to reproduce below:]

1. Selecting any word on any document causes this error to come up
2. This also happens when I try to "find" or use alt-delete.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [minimap-highlight-selected](https://github.com/atom-minimap/minimap-highlight-selected) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'push' of undefined

```
At /Users/jeremy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78

TypeError: Cannot read property 'push' of undefined
    at /Users/jeremy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78:17
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:9)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2648:26)
    at FakeEditor.(anonymous function) [as scanInBufferRange] (/Users/jeremy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
    at MinimapHighlightSelectedView.handleSelection (/Users/jeremy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
    at MinimapHighlightSelectedView.handleSelection (/Users/jeremy/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /Users/jeremy/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:94:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2626:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:924:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:106:19)
    at DisplayMarker.module.exports.DisplayMarker.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:134:32)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:107:24
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:972:7)
    at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:100:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2188:29
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2540:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2506:35)
    at TextEditor.module.exports.TextEditor.setSelectedBufferRanges (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2181:19)
    at TextEditor.module.exports.TextEditor.setSelectedBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2164:19)
    at TextEditor.module.exports.TextEditor.setSelectedScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2213:19)
    at FindView.module.exports.FindView.selectMarkerAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:735:16)
    at FindView.module.exports.FindView.selectFirstMarkerAfterCursor (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:601:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:59
    at FindView.module.exports.FindView.findAndSelectResult (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:485:9)
    at FindView.findAndSelectResult (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:59)
    at FindView.module.exports.FindView.findNext (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:467:19)
    at FindView.findNext (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:3:59)
    at FindView.module.exports.FindView.confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:422:19)
    at atom-text-editor.subscriptions.add.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/find-view.js:274:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:02.2.0 core:save (input.hidden-input)
     -3:00.2.0 find-and-replace:show (input.hidden-input)
     -3:00.0 core:paste (input.hidden-input)
     -2:58.9.0 core:confirm (input.hidden-input)
     -2:47.7.0 core:save (input.hidden-input)
     -0:43.5.0 find-and-replace:show (input.hidden-input)
     -0:41.6.0 core:confirm (input.hidden-input)
     -0:29 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:27.9.0 editor:consolidate-selections (input.hidden-input)
     -0:27.9.0 core:cancel (input.hidden-input)
     -0:25.9.0 find-and-replace:show (input.hidden-input)
  2x -0:23 core:confirm (input.hidden-input)
     -0:10.2.0 editor:consolidate-selections (input.hidden-input)
     -0:10.2.0 core:cancel (input.hidden-input)
     -0:00.9.0 find-and-replace:show (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.2.3 (active)
highlight-selected, v0.12.0 (active)
minimap, v4.26.5 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
wordcount, v2.10.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by JeremyIglehart** [comment]
I'm going to uninstall and reinstall the package.

**Comment by JeremyIglehart** [comment]
That didn't work.  I'm going to have to uninstall this until this is fixed.

**Comment by richrace** [comment]
I updated `highlight-selected` package which includes a new API and uses the new MarkerLayer API. This branch https://github.com/atom-minimap/minimap-highlight-selected/tree/feature-highlight-selected-api needs to be merged into master and published.

**Comment by avindra** [comment]
Dupe of #26

**Comment by haoranw** [comment]
same

**Comment by ecmadao** [comment]
Same for me, with highlight-selected package v0.12.0, minimap-highlight-selected v4.4.0, atom v1.13.0 in macOS Sierra.

**Comment by abe33** [comment]
Hi there, I just published v4.5.0 that includes the enhancements provided by @richrace, let me know if it fixed things for you.

**Comment by ecmadao** [comment]
@abe33 
Cool. Fixed for me.

**Comment by KTsarlz** [comment]
Mine still doesn't work, when highlightning text, there's no hightlight indicator but in the minimap. it does appear. Please look into this @abe33

**Comment by ryanhamley** [comment]
I just updated to v4.5.0 and still get this error with any highlight. I've had to disable the package for the time being to be able to use Atom.

**Comment by KTsarlz** [comment]
@ryanhamley Got it working somehow, I downgraded this package, updated atom and all other packages, and somehow, the highlighting now works.

**Comment by richrace** [comment]
You need to have `highlight-selected v0.12`  

https://github.com/richrace/highlight-selected

**Comment by JeremyIglehart** [comment]
Thanks @richrace All is well now - this is working since I've updated `highlight-selected` and using the current version of `minimap-highlight-selected`.  Closing the issue.  If you're still experiencing this issue - please reopen.
